// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_log_lik_matrix
NumericMatrix compute_log_lik_matrix(NumericMatrix resp_safe, LogicalMatrix obs_mat, NumericMatrix a_i, NumericMatrix b_i, NumericMatrix nodes_g, IntegerVector g_int);
RcppExport SEXP _iDIFr_compute_log_lik_matrix(SEXP resp_safeSEXP, SEXP obs_matSEXP, SEXP a_iSEXP, SEXP b_iSEXP, SEXP nodes_gSEXP, SEXP g_intSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type resp_safe(resp_safeSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type obs_mat(obs_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type a_i(a_iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_i(b_iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type nodes_g(nodes_gSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g_int(g_intSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_log_lik_matrix(resp_safe, obs_mat, a_i, b_i, nodes_g, g_int));
    return rcpp_result_gen;
END_RCPP
}
// nr_update_pooled
NumericVector nr_update_pooled(NumericVector x, NumericMatrix post, NumericMatrix nodes_ik, double a, double b, bool fix_a, bool fix_b, int max_nr, double tol_nr);
RcppExport SEXP _iDIFr_nr_update_pooled(SEXP xSEXP, SEXP postSEXP, SEXP nodes_ikSEXP, SEXP aSEXP, SEXP bSEXP, SEXP fix_aSEXP, SEXP fix_bSEXP, SEXP max_nrSEXP, SEXP tol_nrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type post(postSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type nodes_ik(nodes_ikSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type fix_a(fix_aSEXP);
    Rcpp::traits::input_parameter< bool >::type fix_b(fix_bSEXP);
    Rcpp::traits::input_parameter< int >::type max_nr(max_nrSEXP);
    Rcpp::traits::input_parameter< double >::type tol_nr(tol_nrSEXP);
    rcpp_result_gen = Rcpp::wrap(nr_update_pooled(x, post, nodes_ik, a, b, fix_a, fix_b, max_nr, tol_nr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_iDIFr_compute_log_lik_matrix", (DL_FUNC) &_iDIFr_compute_log_lik_matrix, 6},
    {"_iDIFr_nr_update_pooled", (DL_FUNC) &_iDIFr_nr_update_pooled, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_iDIFr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
