# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_log_lik_matrix <- function(resp_safe, obs_mat, a_i, b_i, nodes_g, g_int) {
    .Call(`_iDIFr_compute_log_lik_matrix`, resp_safe, obs_mat, a_i, b_i, nodes_g, g_int)
}

nr_update_pooled <- function(x, post, nodes_ik, a, b, fix_a = FALSE, fix_b = FALSE, max_nr = 20L, tol_nr = 1e-5) {
    .Call(`_iDIFr_nr_update_pooled`, x, post, nodes_ik, a, b, fix_a, fix_b, max_nr, tol_nr)
}

